# WARNING - Generated by {fusen} from dev/flat_raster_to_points.Rmd: do not edit by hand

library(testthat)
library(raster)
library(sf)
library(sp)

test_that("create_shapefile_from_raster works correctly", {
  # Créez un raster temporaire pour le test
  raster_path <- tempfile(fileext = ".tif")
  shapefile_path <- tempfile(fileext = ".shp")
  
  # Générer un raster simple pour les tests
  r <- raster(nrow=10, ncol=10)
  values(r) <- 1:ncell(r)
  writeRaster(r, raster_path, format="GTiff", overwrite=TRUE)
  
  # Appeler la fonction pour créer le shapefile
  raster2points(raster_path, shapefile_path)
  
  # Vérifiez que le shapefile a été créé
  expect_true(file.exists(shapefile_path))
  
  # Charger le shapefile et vérifier son contenu
  shapefile_points <- st_read(shapefile_path)
  expect_equal(nrow(shapefile_points), ncell(r))
  
  # Vérifiez que les valeurs des pixels sont correctement attribuées aux points
  raster_values <- getValues(r)
  shapefile_values <- shapefile_points$values
  expect_equal(raster_values, shapefile_values)
})

test_that("create_shapefile_from_raster handles errors gracefully", {
  # Test avec un chemin raster incorrect
  expect_error(
    raster2points("non_existent_file.tif", tempfile(fileext = ".shp")),
    "The raster file does not exist."
  )
  
  # Test avec un chemin shapefile incorrect
  raster_path <- tempfile(fileext = ".tif")
  r <- raster(nrow=10, ncol=10)
  values(r) <- 1:ncell(r)
  writeRaster(r, raster_path, format="GTiff", overwrite=TRUE)
  expect_error(
    raster2points(raster_path, "/non_existent_directory/points.shp"),
    "The directory for the shapefile does not exist."
  )
})
