# WARNING - Generated by {fusen} from dev/flat_raster_to_points.Rmd: do not edit by hand

#' This function takes a raster file as input and generates a shapefile with points corresponding to the raster's pixel values.
#'
#' @param raster_path A character string specifying the path to the input raster file.
#' @param shapefile_path A character string specifying the path to save the output shapefile.
#' @importFrom raster raster xyFromCell getValues
#' @importFrom sf st_as_sf st_write
#' @importFrom sp coordinates proj4string
#' @export
#' @examples
#' # Créer un raster simple pour l'exemple
#'
#' library(raster)
#' library(sf)
#' library(sp)
#' raster_path <- tempfile(fileext = ".tif")
#' r <- raster(nrow = 10, ncol = 10, xmn = 0, xmx = 10, ymn = 0, ymx = 10)
#' values(r) <- 1:ncell(r)
#' writeRaster(r, raster_path, format = "GTiff", overwrite = TRUE)
#'
#' # Définir le chemin pour le shapefile de sortie
#' shapefile_path <- tempfile(fileext = ".shp")
#'
#' # Utiliser la fonction pour créer le shapefile à partir du raster
#' raster2points(raster_path, shapefile_path)
#'
#' # Charger le shapefile créé pour vérifier son contenu
#' shapefile_points <- st_read(shapefile_path)
#'
#' # Afficher les premières lignes du shapefile pour vérifier
#' print(head(shapefile_points))

raster2points <- function(raster_path, shapefile_path) {
  # Charger les packages nécessaires
  if (!requireNamespace("pacman", quietly = TRUE)) install.packages("pacman")
  pacman::p_load("raster", "sf", "sp")
  
  # Vérifier que le fichier raster existe
  if (!file.exists(raster_path)) {
    stop("The raster file does not exist.")
  }
  
  # Charger le raster
  raster_layer <- raster(raster_path)
  
  # Obtenir les coordonnées des centres des pixels
  coords <- xyFromCell(raster_layer, 1:ncell(raster_layer))
  
  # Extraire les valeurs des pixels
  values <- getValues(raster_layer)
  
  # Créer un dataframe avec les coordonnées et les valeurs
  points_df <- data.frame(coords, values)
  
  # Convertir le dataframe en SpatialPointsDataFrame
  coordinates(points_df) <- ~ x + y
  proj4string(points_df) <- crs(raster_layer)  # Assigner le CRS du raster au SpatialPointsDataFrame
  
  # Vérifier que le répertoire pour le shapefile existe
  shapefile_dir <- dirname(shapefile_path)
  if (!dir.exists(shapefile_dir)) {
    stop("The directory for the shapefile does not exist.")
  }
  
  # Sauvegarder la couche de points dans un fichier shapefile
  shapefile(points_df, shapefile_path)
}

